### PR TITLE
Add: URL for download log file

### LINKED ISSUE #8: Feature idea: download log files
Hi,

It would be nice to have a download button next to the .log files to be able to download the entire files for further investigation.
Great work by the way, keep going!

### PR DESCRIPTION
**Pull request by kwangsooshin**
resolved #8

1. Add URL for download all log file (`log_viewer/download.zip`)
2. Add URL for download each log file (`log_viewer/download/{file_name}`)
3. code refactoring
    * class TemplateView(_TemplateView) -> to reuse view code
    * move get_log_files function -> to reuse function code

### CODE REVIEW

**Comment by agusmakmun** [comment]
@kwangsooshin thank for the new PR. does it download for all logs? can you change it please to "download per-file" and add button download into template.

**Comment by kwangsooshin** [comment]
> @kwangsooshin thank for the new PR. does it download for all logs? can you change it please to "download per-file" and add button download into template.

@agusmakmun I can make links for download each log file. But I don't know to add button download into template. So, Can you add a download button?

**Comment by agusmakmun** [comment]
@kwangsooshin for sure. you just need to add the download links to go it. then I render it at the template.

**Comment by kwangsooshin** [comment]
@agusmakmun It is completed. Add URL for downloading each log file. It is worked by: `download/{file_name}`

**Comment by kwangsooshin** [comment]
wait for a moment plz

**Comment by kwangsooshin** [comment]
It is done!

**Comment by agusmakmun** [comment]
Here we go, now you can use it @kwangsooshin :tada: :tada: :tada: 


```
pip install django-log-viewer --upgrade
```

**Pull request merged**
