### PR TITLE
Add: LOG_VIEWER_FILES_PATTERN

### LINKED ISSUE #9: Support TimedRotatingFileHandler log
Hi, I use [`TimedRotatingFileHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler)  now.

It generates timed rotating log files and it is renamed log file such as:

```
daily.log.2020-08-25
daily.log.2020-08-26
daily.log.2020-08-27
```

But in this case, I can't show all logs files in the log viewer.

Any method that I see all of logs in the directory?

### PR DESCRIPTION
**Pull request by kwangsooshin**
resolved #9

### CODE REVIEW

**Comment by agusmakmun** [comment]
@kwangsooshin thank you for your PR. But, can you change it into pattern please? for example:

Inside the `settings.py`

```
LOG_VIEWER_FILES_PATTERN = '*.log'
```

Or;

```
LOG_VIEWER_FILES_PATTERN = '*.log*'
```

> So, the developers can custom it pattern by self. And I think it become futuristic solution. \
> Somethime developers doesn't need to show their `.log.backup` file.

To solve this, you can use the [`glob`](https://docs.python.org/3/library/glob.html) module.

```python
>>> import glob
>>> glob.glob('*.log*')
['request.log', 'postgresql.log', 'note.log.2020']
>>>
```

So, inside the `log_viewer/views.py`

```python
import glob

....

glob_path = os.path.join(settings.LOG_VIEWER_FILES_DIR, settings.LOG_VIEWER_FILES_PATTERN)
tmp_names = [name for name in tmp_names if name in glob.glob(glob_path)]

# also try with this below:
# (I don't know it will return the same output or not)

glob_path = os.path.join(settings.LOG_VIEWER_FILES_DIR, settings.LOG_VIEWER_FILES_PATTERN)
tmp_names = glob.glob(glob_path)
```

**Comment by kwangsooshin** [comment]
@agusmakmun Your method is more elegant! Got it.

**Comment by kwangsooshin** [comment]
@agusmakmun How about this? It is better than using [`fnmatch`](https://docs.python.org/3/library/fnmatch.html#fnmatch.fnmatch).

**Comment by agusmakmun** [comment]
@kwangsooshin that's great, it one of other solution to. Does this working, and ready to merge?

**Comment by kwangsooshin** [comment]
@agusmakmun Yes. It ready to merge. Could you release new version including this version? Becuase, I need this for my project.

**Comment by agusmakmun** [comment]
@kwangsooshin for sure. Now available at [pypi](https://pypi.org/project/django-log-viewer/1.0.8/).

```
pip install django-log-viewer==1.0.8
```

or;

```
pip install django-log-viewer --upgrade
```

**Pull request merged**
